### ISSUE TITLE
Allow macos “middle mouse click” panning alternative using keyboard

### ISSUE THREAD

**Issue by mgi388** [Plonq/bevy_rts_camera#19]
Out of the box, middle mouse click works great when your mouse is connected. When on the laptop trackpad only I don’t think panning has an equivalent action. 

It would be cool if you could shift and move two fingers to pan. I think this is what blender does, but any action common to RTS games on laptops would work.

**Comment by Plonq** [comment]
Hi. Thanks for the suggestion, but I don't plan to implement something like that. You can pan 3 different ways - keyboard, edge, and drag. Mouse is only really required for drag (presuming you can't use left/right click), so it's not like it's unusable without a mouse or anything.

This plugin is intentionally very simple and doesn't try to cover every use case. If you need advanced controls, I suggest rolling your own controller instead of using the built in one.

**Comment by jonathaningram** [comment]
@Plonq of course, just a suggestion. Thanks.

**Comment by mgi388** [comment]
@Plonq of course, just a suggestion. Thanks.
